In [1]:
!pip install nltk snowballstemmer pymorphy2 pymystem3 gensim

     |████████████████████████████████| 61kB 2.7MB/s 
     |████████████████████████████████| 8.2MB 2.1MB/s 


In [2]:
try:
    from google.colab import drive
    import os
    drive.mount('/content/drive')
    os.chdir('/content/drive/My Drive/6_laba/')
except ImportError:
    pass

Mounted at /content/drive


# **Предобработка текстов**
Поскольку в русском языке много словоформ, прежде всего нужно преобразовать все тексты к единому виду.

Считаем один из файлов и посмотрим, что мы можем с ним сделать

In [3]:
with open("Onegin/oneg_1.txt", encoding="utf8") as f:
    example_text = f.read()

example_text

'\n\nHe мысля гордый свет забавить,\n\nВниманье дружбы возлюбя,\n\nХотел бы я тебе представить\n\nЗалог достойнее тебя,\n\nДостойнее души прекрасной,\n\nСвятой исполненной мечты,\n\nПоэзии живой и ясной,\n\nВысоких дум и простоты;\n\nНо так и быть – рукой пристрастной\n\nПрими собранье пестрых глав,\n\nПолусмешных, полупечальных,\n\nПростонародных, идеальных,\n\nНебрежный плод моих забав,\n\nБессонниц, легких вдохновений,\n\nНезрелых и увядших лет,\n\nУма холодных наблюдений\n\nИ сердца горестных замет.\n\n\n\n\n\nГлава первая\n\n\n\n\nИ жить торопится, и чувствовать спешит.\n\nКнязь Вяземский[2]\n\n\n\n\n\nI\n\n\n\n\n«Мой дядя самых честных правил,\n\nКогда не в шутку занемог,\n\nОн уважать себя заставил\n\nИ лучше выдумать не мог.\n\nЕго пример другим наука;\n\nНо, боже мой, какая скука\n\nС больным сидеть и день и ночь,\n\nНе отходя ни шагу прочь!\n\nКакое низкое коварство\n\nПолуживого забавлять,\n\nЕму подушки поправлять,\n\nПечально подносить лекарство,\n\nВздыхать и думать про с

Токенизация текста - просто выделение оттуда отдельных слов. Обратите внимание, они не приводятся к одному регистру, знаки препинания не удаляются.

In [4]:
import nltk
nltk.download('punkt')
tokens = nltk.word_tokenize(example_text)
tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['He',
 'мысля',
 'гордый',
 'свет',
 'забавить',
 ',',
 'Вниманье',
 'дружбы',
 'возлюбя',
 ',',
 'Хотел',
 'бы',
 'я',
 'тебе',
 'представить',
 'Залог',
 'достойнее',
 'тебя',
 ',',
 'Достойнее',
 'души',
 'прекрасной',
 ',',
 'Святой',
 'исполненной',
 'мечты',
 ',',
 'Поэзии',
 'живой',
 'и',
 'ясной',
 ',',
 'Высоких',
 'дум',
 'и',
 'простоты',
 ';',
 'Но',
 'так',
 'и',
 'быть',
 '–',
 'рукой',
 'пристрастной',
 'Прими',
 'собранье',
 'пестрых',
 'глав',
 ',',
 'Полусмешных',
 ',',
 'полупечальных',
 ',',
 'Простонародных',
 ',',
 'идеальных',
 ',',
 'Небрежный',
 'плод',
 'моих',
 'забав',
 ',',
 'Бессонниц',
 ',',
 'легких',
 'вдохновений',
 ',',
 'Незрелых',
 'и',
 'увядших',
 'лет',
 ',',
 'Ума',
 'холодных',
 'наблюдений',
 'И',
 'сердца',
 'горестных',
 'замет',
 '.',
 'Глава',
 'первая',
 'И',
 'жить',
 'торопится',
 ',',
 'и',
 'чувствовать',
 'спешит',
 '.',
 'Князь',
 'Вяземский',
 '[',
 '2',
 ']',
 'I',
 '«',
 'Мой',
 'дядя',
 'самых',
 'честных',
 'правил',
 ',',
 '

И теперь посмотрим, как морфоанализатор сможет преобразовать наш исходный текст

In [5]:
import pymorphy2
morph = pymorphy2.MorphAnalyzer()
lemm_pymorph = [morph.parse(s)[0].normal_form for s in tokens[:200]]
lemm_pymorph

['he',
 'мыслить',
 'гордый',
 'свет',
 'забавить',
 ',',
 'внимание',
 'дружба',
 'возлюбя',
 ',',
 'хотеть',
 'бы',
 'я',
 'ты',
 'представить',
 'залог',
 'достойный',
 'ты',
 ',',
 'достойный',
 'душа',
 'прекрасный',
 ',',
 'святой',
 'исполнить',
 'мечта',
 ',',
 'поэзия',
 'живой',
 'и',
 'ясный',
 ',',
 'высокий',
 'дума',
 'и',
 'простота',
 ';',
 'но',
 'так',
 'и',
 'быть',
 '–',
 'рука',
 'пристрастный',
 'принять',
 'собрание',
 'пёстрый',
 'глава',
 ',',
 'полусмешной',
 ',',
 'полупечальный',
 ',',
 'простонародный',
 ',',
 'идеальный',
 ',',
 'небрежный',
 'плод',
 'мой',
 'забава',
 ',',
 'бессонница',
 ',',
 'лёгкий',
 'вдохновение',
 ',',
 'незрелый',
 'и',
 'увядший',
 'год',
 ',',
 'ум',
 'холодный',
 'наблюдение',
 'и',
 'сердце',
 'горестный',
 'замета',
 '.',
 'глава',
 'первый',
 'и',
 'жить',
 'торопиться',
 ',',
 'и',
 'чувствовать',
 'спешить',
 '.',
 'князь',
 'вяземский',
 '[',
 '2',
 ']',
 'i',
 '«',
 'мой',
 'дядя',
 'самый',
 'честной',
 'правило',
 ','

Чтобы снова собрать из этого, текст, просто сконкатенируем все получившиеся строки:

In [6]:
' '.join(lemm_pymorph)

'he мыслить гордый свет забавить , внимание дружба возлюбя , хотеть бы я ты представить залог достойный ты , достойный душа прекрасный , святой исполнить мечта , поэзия живой и ясный , высокий дума и простота ; но так и быть – рука пристрастный принять собрание пёстрый глава , полусмешной , полупечальный , простонародный , идеальный , небрежный плод мой забава , бессонница , лёгкий вдохновение , незрелый и увядший год , ум холодный наблюдение и сердце горестный замета . глава первый и жить торопиться , и чувствовать спешить . князь вяземский [ 2 ] i « мой дядя самый честной правило , когда не в шутка занемочь , он уважать себя заставить и хороший выдумать не мочь . он пример другой наука ; но , бог мой , какой скука с больной сидеть и день и ночь , не отходить ни шаг прочь ! какой низкий коварство полуживой забавлять , он подушка поправлять , печально подносить лекарство , вздыхать и думать про себя : когда же черта взять ты ! » ii так думать молодой повеса , лететь в пыль на почтовый 

## **Формирование выборки сырых данных**

Обернем наши предыдущие действия в функцию:

In [7]:
from string import punctuation

def lemmatize(input_text):
    tokens = nltk.word_tokenize(input_text)
    normed_tokens = [morph.parse(s)[0].normal_form for s in tokens]
    # исключим также стоп-слова - всякие предлоги, союзы и т.п.
    normed_tokens = [word for word in normed_tokens if word not in nltk.corpus.stopwords.words("russian")]
    # а также знаки препинания
    normed_tokens = [word for word in normed_tokens if word not in punctuation]
    return ' '.join(normed_tokens)

Рассмотрим задачу бинарной классификации текстов. Возьмем Евгения Онегина и книжонку из серии Попаданец и попробуем подобрать такой алгоритм, который смог бы их отличать друг от друга.

In [8]:
import os
import pandas as pd
import nltk
nltk.download('stopwords')

# подготовим пустой датафрейм
df = pd.DataFrame(columns=['text', 'class'])

# это папки, в которых лежат файлы с текстами
dir0 = "Onegin"
dir1 = "popadanec"

# считаем все наши тексты в датафрейм с указанием класса
for filename in os.listdir(dir0):
    with open(os.path.join(dir0, filename), encoding='utf8') as file:
        contents = lemmatize(file.read())
    df = df.append(pd.Series({'text': contents, 'class': 0}), ignore_index=True)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [9]:
# и для второй папки тоже
for filename in os.listdir(dir1):
    with open(os.path.join(dir1, filename), encoding='utf8') as file:
        contents = lemmatize(file.read())
    df = df.append(pd.Series({'text': contents, 'class': 1}), ignore_index=True)

Посмотрим на вид нашего датафрейма

In [10]:
df

text class
0   шалун заморозить пальчик больно смешно мать гр...     0
1   16 читатель помнить прелестный описание петерб...     0
2   меж невидимый расти темнеть вечер синий пора о...     0
3   томный волнение душа кровь тяжёлый умиление на...     0
4   любить ричардсон прочесть грандисон ловлас пре...     0
..                                                ...   ...
95  первый взгляд внутри корабль принципиально отл...     1
96  крышка капсула медленно пойти вверх открывать ...     1
97  глава 4 сенсор настроить пассивный режим выдат...     1
98  следующий номер план стоять покупка новый моде...     1
99  самый главное это несмотря увеличение длина ст...     1

[100 rows x 2 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['class'], test_size=0.12, stratify=df['class'])

# Bag-of-Words-эмбеддинг
Pаботать с чистым текстом математические методы не умеют. Настало время получить эмбеддинги

In [12]:
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
bof_vect = CountVectorizer()
bof_vect.fit(np.hstack([X_train, X_test]))
bof_train = bof_vect.transform(X_train)
bof_test = bof_vect.transform(X_test)

In [13]:
bof_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
bof_train.toarray().shape

(88, 10101)

# TF-IDF-эмбеддинг

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(np.hstack([X_train, X_test]))
tfidf_train = tfidf_vect.transform(X_train)
tfidf_test = tfidf_vect.transform(X_test)

In [17]:
tfidf_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
tfidf_train.toarray().shape

(88, 10101)

# Word2vec-эмбеддинг
Поскольку w2v - это не sklearn'овский классификатор, он на выходе выдаст данные немного другого вида, и это надо будет учитывать в дальнейшей работе

In [19]:
from gensim.models import Word2Vec
X_train_w2v = X_train.apply(str.split)
X_test_w2v = X_test.apply(str.split)
w2v_vect = Word2Vec(np.hstack([X_train_w2v, X_test_w2v]), size=300, min_count=10, workers=8)

In [20]:
X_train_w2v

10    [xiii, ленский, иметь, охота, уза, брак, несть...
80    [—, лейтенант-коммандер, —, уточнить, я., это,...
60    [хрен, сколько, тысячелетие, сильно, большой, ...
31    [усеять, плошка, кругом, блестеть, великолепны...
81    [платформа, представлять, круг, диаметр, метр,...
                            ...                        
46    [весна, клик, лебединый, близ, вода, сиять, ти...
62    [знак, свой, беспомощность, развести, сторона,...
78    [ива, остановить, жест, —, спасибо, легат, цен...
18    [мы…, ничто, блестеть, рада, простодушно, посе...
90    [склонить, голова, ответный, поклон, —, честь,...
Name: text, Length: 88, dtype: object

С ворд-ту-веком можно делать разные интересные вещи. Например, следующей командой мы можем вывести слова, которые оказались наиболее близкими по значению к заданному слову на обучающей выборке

In [21]:
w2v_vect.most_similar(positive="человек")

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('ещё', 0.9999793171882629),
 ('весь', 0.99997878074646),
 ('всё', 0.9999784231185913),
 ('это', 0.9999773502349854),
 ('—', 0.9999769926071167),
 ('свой', 0.9999765157699585),
 ('корабль', 0.9999746084213257),
 ('мочь', 0.9999736547470093),
 ('душа', 0.9999731183052063),
 ('год', 0.9999727010726929)]

Преобразуем тексты в вектора - возьмем сумму векторов всех слов, которые входят в текст

In [22]:
def text2vec(text):
    """Усредняем векторы слов"""
    vecs = []
    for word in text:
        try:
            vecs.append(w2v_vect[word])
        except KeyError:
            pass
    return np.sum(vecs, axis=0) / len(vecs)

w2v_train = X_train_w2v.apply(text2vec)
w2v_test = X_test_w2v.apply(text2vec)
w2v_train

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


10    [0.096241556, -0.14170004, -0.057885505, -0.05...
80    [0.10327929, -0.15214378, -0.06206952, -0.0552...
60    [0.10208867, -0.15050392, -0.061551485, -0.054...
31    [0.08031369, -0.118201785, -0.048475277, -0.04...
81    [0.088913046, -0.13082908, -0.053259987, -0.04...
                            ...                        
46    [0.08086777, -0.11894336, -0.04872365, -0.0433...
62    [0.09612576, -0.14146197, -0.05774134, -0.0516...
78    [0.09840897, -0.1447756, -0.05923165, -0.05275...
18    [0.101684034, -0.15004024, -0.061538562, -0.05...
90    [0.08716605, -0.1285638, -0.052426126, -0.0468...
Name: text, Length: 88, dtype: object

In [23]:
w2v_train.shape

(88,)

In [24]:
w2v_train[0]

KeyError: ignored

In [25]:
w2v_train = np.dstack(w2v_train)[0]
w2v_train.shape

(300, 88)

In [26]:
w2v_test = np.dstack(w2v_test)[0]

# Классификация текстов
Теперь у нас есть классическое признаковое описание каждого текста. Можем обучать классификаторы или придумать еще какую-то метрику.

Давайте вычислим для каждого эмбеддинга по два суммарных вектора Для Bag of Words:

In [33]:
b=y_train == 0
a=bof_train[b[len(b)]]
oneg_mean_bof = np.sum(a, axis=0)
oneg_mean_bof.shape

(1, 10101)

In [34]:
d=y_train == 1
c=bof_train[d[len(d)]]
pop_mean_bof = np.sum(c, axis=0)

Для TF-IDF

In [35]:
b=y_train == 0
a=tfidf_train[b[len(b)]]
oneg_mean_tfidf = np.sum(a, axis=0)
oneg_mean_tfidf.shape

(1, 10101)

In [36]:
d=y_train == 1
c=tfidf_train[d[len(d)]]
pop_mean_tfidf = np.sum(c, axis=0)

Для Word2Vec

In [37]:
oneg_mean_w2v = np.sum(w2v_train[:, y_train == 1], axis=1)
oneg_mean_w2v.shape

(300,)

In [38]:
pop_mean_w2v = np.sum(w2v_train[:, y_train == 0], axis=1)

Посмотрим на их вид:

In [39]:
oneg_mean_bof

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
oneg_mean_tfidf

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [41]:
oneg_mean_w2v

array([  4.297532  ,  -6.3319516 ,  -2.5813491 ,  -2.3018336 ,
        -5.175403  ,  -4.3950944 ,   4.9457664 ,  -5.03447   ,
         4.3867345 ,   1.0973651 ,  -1.1242104 ,   8.487882  ,
         0.8259996 ,  -4.703243  ,  -5.723107  , -13.366727  ,
        -2.3294013 ,   4.043012  ,  -4.7797093 ,  -6.0962663 ,
        -2.8844419 ,   2.0650856 ,   4.367884  ,  13.134641  ,
         3.1744232 ,  -2.6749132 ,   0.34669584,   3.9526758 ,
         5.2513046 , -14.059929  ,  -2.6032097 ,   3.5150933 ,
         0.06490763,   3.7994895 ,   9.239856  ,  -6.631697  ,
         0.4333183 ,   3.4581356 ,   1.1223385 , -15.98746   ,
        -6.0669813 ,  -6.758249  ,   1.0637025 ,  -1.4383658 ,
         7.9644117 , -10.411005  ,  -2.5322297 , -12.239351  ,
         4.3995614 ,  -5.702172  ,  -5.207567  ,   1.6836512 ,
        -7.4332542 ,  -7.339035  ,   7.1731744 ,   3.6311154 ,
        11.9297495 ,   4.8779807 ,  -6.459734  ,   7.4495134 ,
         9.328403  ,  -4.973703  ,  12.565379  ,  -7.01

А теперь построим датафреймы с результатами классификации тестовых текстов. Будем считать, что текст относится к тому исполнителю, с которым его косинусное расстояние больше.

In [42]:
from scipy.spatial.distance import cosine

In [43]:
bof_oneg = np.apply_along_axis(cosine, 1, bof_test.toarray(), v=oneg_mean_bof)
bof_pop = np.apply_along_axis(cosine, 1, bof_test.toarray(), v=pop_mean_bof)

bof_results = pd.DataFrame([
    bof_oneg,
    bof_pop,
    np.maximum(bof_oneg, bof_pop) == bof_pop,
    y_test
], index=["oneg", "pop", "predict", "class"]).T.astype(np.float)
bof_results

oneg       pop  predict  class
0   0.800688  0.822247      1.0    0.0
1   0.810771  0.788585      0.0    0.0
2   0.695865  0.806193      1.0    0.0
3   0.808818  0.857083      1.0    0.0
4   0.861201  0.756087      0.0    1.0
5   0.893243  0.683191      0.0    1.0
6   0.885262  0.655895      0.0    1.0
7   0.887680  0.725245      0.0    1.0
8   0.761994  0.862498      1.0    0.0
9   0.893427  0.778873      0.0    1.0
10  0.907589  0.755878      0.0    1.0
11  0.755837  0.846417      1.0    0.0

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(bof_results['predict'], bof_results['class'])

0.08333333333333333

In [45]:
tfidf_oneg = np.apply_along_axis(cosine, 1, tfidf_test.toarray(), v=oneg_mean_tfidf)
tfidf_pop = np.apply_along_axis(cosine, 1, tfidf_test.toarray(), v=pop_mean_tfidf)

tfidf_results = pd.DataFrame([
    tfidf_oneg,
    tfidf_pop,
    np.maximum(tfidf_oneg, tfidf_pop) == tfidf_pop,
    y_test
], index=["oneg", "pop", "predict", "class"]).T.astype(np.float)
tfidf_results

oneg       pop  predict  class
0   0.919880  0.958795      1.0    0.0
1   0.933467  0.947197      1.0    0.0
2   0.859463  0.943444      1.0    0.0
3   0.927808  0.962522      1.0    0.0
4   0.954390  0.911063      0.0    1.0
5   0.964623  0.899351      0.0    1.0
6   0.963830  0.891864      0.0    1.0
7   0.975720  0.880890      0.0    1.0
8   0.879697  0.946846      1.0    0.0
9   0.967019  0.916600      0.0    1.0
10  0.975076  0.927974      0.0    1.0
11  0.885697  0.966178      1.0    0.0

In [46]:
accuracy_score(tfidf_results['predict'], tfidf_results['class'])

0.0

In [48]:
w2v_oneg = np.apply_along_axis(cosine, 0, w2v_test, v=oneg_mean_w2v)
w2v_pop = np.apply_along_axis(cosine, 0, w2v_test, v=pop_mean_w2v)

w2v_results = pd.DataFrame([
    w2v_oneg,
    w2v_pop,
    np.maximum(w2v_oneg, w2v_pop) == w2v_pop,
    y_test
], index=["oneg", "pop", "predict", "class"]).T.astype(np.float)
w2v_results

oneg           pop  predict  class
0   1.311302e-06  2.980232e-07      0.0    0.0
1   1.609325e-06  5.364418e-07      0.0    0.0
2   1.132488e-06  2.980232e-07      0.0    0.0
3   9.536743e-07  4.172325e-07      0.0    0.0
4   2.384186e-07  1.549721e-06      1.0    1.0
5   2.384186e-07  1.728535e-06      1.0    1.0
6   1.788139e-07  1.251698e-06      1.0    1.0
7   3.576279e-07  1.609325e-06      1.0    1.0
8   1.668930e-06  4.172325e-07      0.0    0.0
9   2.980232e-07  1.251698e-06      1.0    1.0
10  4.172325e-07  1.490116e-06      1.0    1.0
11  1.490116e-06  4.768372e-07      0.0    0.0

In [49]:
accuracy_score(w2v_results['predict'], w2v_results['class'])

1.0

In [50]:
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier().fit(bof_train.toarray(), y_train.tolist()).score(bof_test.toarray(), y_test.tolist())

1.0

In [51]:
RandomForestClassifier().fit(tfidf_train.toarray(), y_train.tolist()).score(tfidf_test.toarray(), y_test.tolist())

1.0

In [52]:
RandomForestClassifier().fit(w2v_train.T, y_train.tolist()).score(w2v_test.T, y_test.tolist())

0.8333333333333334

Ближайшие соседи

In [53]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(bof_train.toarray(), y_train.tolist())
clf.score(bof_test.toarray(), y_test.tolist())

0.9166666666666666

In [54]:
clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(tfidf_train.toarray(), y_train.tolist())
clf.score(tfidf_test.toarray(), y_test.tolist())

1.0

In [55]:
clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(w2v_train.T, y_train.tolist())
clf.score(w2v_test.T, y_test.tolist())

0.5

Логистическая регрессия

In [56]:
from sklearn.linear_model import LogisticRegression
lo = LogisticRegression()
lo.fit(bof_train.toarray(), y_train.tolist())
lo.score(bof_test.toarray(), y_test.tolist())

1.0

In [57]:
lo = LogisticRegression()
lo.fit(tfidf_train.toarray(), y_train.tolist())
lo.score(tfidf_test.toarray(), y_test.tolist())

1.0

In [58]:
lo = LogisticRegression()
lo.fit(w2v_train.T, y_train.tolist())
lo.score(w2v_test.T, y_test.tolist())

0.6666666666666666

По итогу, обычные методы классификации показывают результат лучше.